language: java
dist: xenial

jdk:
- openjdk8

env:
  - THRIFT_VERSION=0.12.0

addons:
  apt:
    packages:
    - thrift-compiler

cache:
  directories:
  - "$HOME/.m2"

install: skip

before_script:
#- openssl aes-256-cbc -K $encrypted_d3fff69b07aa_key -iv $encrypted_d3fff69b07aa_iv -in .cd/sign.asc.enc -d | gpg --batch --import
- gpg --recv-keys EDD02683 # James E. King III (CODE SIGNING KEY) <jking@apache.org>
- curl --fail -L -O https://archive.apache.org/dist/thrift/$THRIFT_VERSION/thrift-$THRIFT_VERSION.tar.gz
- curl --fail -L -O https://archive.apache.org/dist/thrift/$THRIFT_VERSION/thrift-$THRIFT_VERSION.tar.gz.asc
- gpg --verify thrift-$THRIFT_VERSION.tar.gz.asc thrift-$THRIFT_VERSION.tar.gz
- tar xzf thrift-$THRIFT_VERSION.tar.gz
- rm -rf thrift-$THRIFT_VERSION.tar.gz.asc thrift-$THRIFT_VERSION.tar.gz

script:
# apply patches
- git apply --directory=thrift-$THRIFT_VERSION patches/*.patch
        #- mvn -B -gs .cd/settings.xml -P release-profile deploy
- mvn -f thrift-$THRIFT_VERSION/contrib/thrift-maven-plugin -P release-profile -Dgpg.skip install

  #before_cache:
  #- gpg --batch --yes --delete-secret-keys $GPG_KEYID
  #- gpg --batch --yes --delete-keys $GPG_KEYID
